#!/bin/bash

#set default values
INSTALL_DIR=/home/$USER

#parse the passed parameters
while getopts d:-/home/$USER option
do
    case "${option}"
    in
        d) INSTALL_DIR=${OPTARG};;
    esac
done

#check if a new volume should be created
if [ -z $(docker volume ls -q) ]
then
    echo "Creating 'excalivol' volume"
    docker volume create excalivol
else
    echo "Volume 'excalivol' already exists"
fi

#check if 'excalihost' database should be created
if [ -z $(docker ps -f name=excalibur -q) ]
then
    echo "Creating 'excalihost' postgres server with 'excalibur' database"
    docker run \
    --rm \
    --name excalihost \
    -e POSTGRES_PASSWORD=postgres \
    -e POSTGRES_DB=excalibur \
    -d \
    -p 5432:5432 \
    -v excalivol:/var/lib/postgresql/data \
    --network=bookingsnet
    postgres
else
    echo "Postgres server 'excalihost' already running"
fi

#create host server
docker build -t katzda/bookings:latest -f ./Dockerfile .

#clean up: stopping previous container
containers_string=$(docker ps -f name=bookings -q)
if [ ${#containers_string} -gt 0 ]
then
    echo "REMOVING 'bookings' CONTAINER:"
    docker rm -f $containers_string
else
    echo "NO RUNNING bookings NEEDS STOPPING"
fi

containers_string=$(docker ps -f "status=exited" -q)
if [ ${#containers_string} -gt 0 ]
then
    IFS=' ' read -a containers <<< $containers_string
    echo "REMOVING ${#containers[@]} CONTAINER(S)):"
    docker rm $containers_string
else
    echo "Containers don't need to be cleaned up."
fi

#clean up: dangling images
images_string=$(docker images -f "dangling=true" -q)
if [ ${#images_string} -gt 0 ]
then
    IFS=' ' read -a images <<< $images_string
    echo "REMOVING ${#images[@]} IMAGE(S):"
    docker rmi -f $images_string
else
    echo "Images don't need to be cleaned up."
fi

#setup the repo
docker run -v $INSTALL_DIR:/home/developer \
           --rm \
           -d \
           --name bookings \
           -p 8080:80 \
           --network=bookingsnet \
           katzda/bookings:latest

cd $INSTALL_DIR
REPO="$INSTALL_DIR/booking-system"
if [ ! -f "$REPO" ]; then
    #We have NOT cloned 'booking-system' before
    echo "Cloning repo to: $INSTALL_DIR/booking-system/"
    if ! (git clone git@github.com:katzda/booking-system.git -b develop) then
        echo "Cloning failed!"

        #it is possible that we have never generated ssh keys
        cd ~/.ssh/
        RSA=$(ls ~/.ssh | grep bookings_rsa)
        if [ ${#RSA} -eq 0 ]
        then
            echo "GENERATING ssh PRIVATE KEY and PUBLIC LOCK"
            ssh-keygen -t rsa -b 4096 -C "bookings github repo" -P "" -f bookings_rsa
            eval $(ssh-agent -s)
            ssh-add ~/.ssh/bookings_rsa
            echo "Host github.com
                    Hostname ssh.github.com
                    StrictHostKeyChecking no
                    Port 443" >> ~/.ssh/config
            ssh -T git@github.com
        else
            echo "PRIVATE KEY and PUBLIC LOCK already exist"
        fi

        echo "You need to register this PUBLIC KEY in your repo:"
        cat ~/.ssh/bookings_rsa.pub
        echo "Then execute this file again."
        return 0
    fi
fi